// This file is generated by zbuild. Do not edit manually.

const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const module_zevm = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("zevm"), module_zevm) catch @panic("OOM");

    const exe_zevm = b.addExecutable(.{
        .name = "zevm",
        .root_module = module_zevm,
    });

    const install_exe_zevm = b.addInstallArtifact(exe_zevm, .{});

    const tls_install_exe_zevm = b.step("build-exe:zevm", "Install the zevm executable");
    tls_install_exe_zevm.dependOn(&install_exe_zevm.step);
    b.getInstallStep().dependOn(&install_exe_zevm.step);

    const run_exe_zevm = b.addRunArtifact(exe_zevm);
    if (b.args) |args| run_exe_zevm.addArgs(args);
    const tls_run_exe_zevm = b.step("run:zevm", "Run the zevm executable");
    tls_run_exe_zevm.dependOn(&run_exe_zevm.step);

    const tls_run_test = b.step("test", "Run all tests");

    const test_zevm = b.addTest(.{
        .name = "zevm",
        .root_module = module_zevm,
        .filters = b.option([][]const u8, "zevm.filters", "zevm test filters") orelse &[_][]const u8{},
    });
    const install_test_zevm = b.addInstallArtifact(test_zevm, .{});
    const tls_install_test_zevm = b.step("build-test:zevm", "Install the zevm test");
    tls_install_test_zevm.dependOn(&install_test_zevm.step);

    const run_test_zevm = b.addRunArtifact(test_zevm);
    const tls_run_test_zevm = b.step("test:zevm", "Run the zevm test");
    tls_run_test_zevm.dependOn(&run_test_zevm.step);
    tls_run_test.dependOn(&run_test_zevm.step);
}
